% Auto-generated by arxml-codegen.
% Run this before updating imported Simulink AUTOSAR models.

if ~exist('ADT_ActiveFlag', 'var')
    ADT_ActiveFlag = Simulink.AliasType;
    ADT_ActiveFlag.BaseType = 'boolean';
end

if ~exist('ADT_Boolean', 'var')
    ADT_Boolean = Simulink.AliasType;
    ADT_Boolean.BaseType = 'boolean';
end

if ~exist('ADT_FWiperCmd', 'var')
    ADT_FWiperCmd = Simulink.AliasType;
    ADT_FWiperCmd.BaseType = 'uint8';
end

if ~exist('ADT_FWiperSWSts', 'var')
    ADT_FWiperSWSts = Simulink.AliasType;
    ADT_FWiperSWSts.BaseType = 'uint8';
end

if ~exist('ADT_FWiperSts', 'var')
    ADT_FWiperSts = Simulink.AliasType;
    ADT_FWiperSts.BaseType = 'uint8';
end

if ~exist('ADT_FaultFlag', 'var')
    ADT_FaultFlag = Simulink.AliasType;
    ADT_FaultFlag.BaseType = 'boolean';
end

if ~exist('ADT_InhibitSts', 'var')
    ADT_InhibitSts = Simulink.AliasType;
    ADT_InhibitSts.BaseType = 'boolean';
end

if ~exist('ADT_OnOff', 'var')
    ADT_OnOff = Simulink.AliasType;
    ADT_OnOff.BaseType = 'boolean';
end

if ~exist('ADT_RainSensitivity', 'var')
    ADT_RainSensitivity = Simulink.AliasType;
    ADT_RainSensitivity.BaseType = 'uint8';
end

if ~exist('ADT_ReturnCode', 'var')
    ADT_ReturnCode = Simulink.AliasType;
    ADT_ReturnCode.BaseType = 'uint8';
end

if ~exist('ADT_Uint16', 'var')
    ADT_Uint16 = Simulink.AliasType;
    ADT_Uint16.BaseType = 'uint16';
end

if ~exist('ADT_Uint8', 'var')
    ADT_Uint8 = Simulink.AliasType;
    ADT_Uint8.BaseType = 'uint8';
end
