% Auto-generated by arxml-codegen.
% Run this before updating imported Simulink AUTOSAR models.

if ~exist('ADT_FWasherCmd', 'var')
    ADT_FWasherCmd = Simulink.AliasType;
    ADT_FWasherCmd.BaseType = 'boolean';
end

if ~exist('ADT_FWasherOutput', 'var')
    ADT_FWasherOutput = Simulink.AliasType;
    ADT_FWasherOutput.BaseType = 'boolean';
end

if ~exist('ADT_ReturnCode', 'var')
    ADT_ReturnCode = Simulink.AliasType;
    ADT_ReturnCode.BaseType = 'uint8';
end
